### PR TITLE
Add support for start, increment and functions to range filter.

### PR DESCRIPTION
**Pull request by dopry**
This PR adds support for start, increment, and custom functions to the range filter.

It allows you to generate more complex series.  Currently you can only create the set 0..n.

This expands the input to range from just the length of the range to generate to length, start, and increment, and function. The range filter will generate a set starting at start (defaults to 0) for length iterations, incrementing by increment for each iteration, and if a function is supplied, passing the value to the function.

this allows you to create sets such as
[10..20], | range:10:10
[10,12,14,16,18], | range:10:5:2
[11,13,15,17], | range:11:4:2 

examine the tests for more details.

### CODE REVIEW

**Comment by dopry** [comment]
@a8m, hey wanted to see if this was something you're interested in merging.  Let me know if you would like to see any changes or modifications. I've preserved backwards compatibility.

**Comment by dopry** [comment]
@a8m, ping. I wanted to follow up and see if there was a chance of getting this included. I'd rather not maintain a personal fork unless necessary.

**Comment by simonered** [comment]
Please merge

**Comment by dopry** [comment]
@a8m what feedback are you looking for?

**Comment by a8m** [comment]
I'm planning to review this PR today. can you please update the README?
thanks @dopry

**Comment by dopry** [comment]
I rebased and updates the README.md. I'm out tomorrow, but if you review I
can address any issues on Thursday.

**Pull request merged**
